### PR TITLE
Fix wrongly parse `+1` as a number in expression: `1+1`

### LINKED ISSUE #90: [Bug] Unable to parse simple SQL statements
```sql
select 1+1;

<EOF> or ';' was expected, but got: "+1"
        select 1+1;
```

```sql
# select case when false then 'hello' else 'world' end;

expected keyword: END, but got <keyword>
        select case when false then 'hello' else 'world' end;
                         ^^^^^
```

### PR DESCRIPTION
**Pull request by git-hulk**
This PR closes #90

### CODE REVIEW

File: parser/testdata/query/format/select_when_condition.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+-- Origin SQL:
+select case when false then 'hello' else 'world' end;
+
+-- Format SQL:
+
+SELECT 
+  CASE WHEN false THEN 'hello'ELSE 'world'END;
```
Comment (Lance726) [inline parser/testdata/query/format/select_when_condition.sql:7]: It seems the space missing between 'hello' and ELSE.

Comment (git-hulk) [reply parser/testdata/query/format/select_when_condition.sql:7]: Yes, good catch.

**Review by Lance726 — APPROVED** [review]
